import type { Metadata } from "next";

import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        style={{
          height: "100dvh",
          display: "flex",
          flexDirection: "column",
        }}
      >
        <h1
          style={{
            backgroundColor: "#c4f551",
            padding: "0.5em",
          }}
        >
          ARF
        </h1>

        <div
          style={{
            backgroundColor: "black",
            flex: 1,
          }}
        >
          {children}
        </div>
      </body>
    </html>
  );
}
